# Generated by Django 3.0.5 on 2024-04-20 00:57

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20230924_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='codigo',
            field=models.CharField(default=builtins.all, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='tipo',
            field=models.CharField(default=builtins.all, max_length=10),
            preserve_default=False,
        ),
    ]
