# Generated by Django 3.0.5 on 2024-04-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20240419_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='tipo',
            field=models.CharField(max_length=15),
        ),
    ]
